'''print(".\t\t.")
print("\tU")
print("")
print("X X")
print(" X")
print("X X")
print("")
print("-----")
print("v   v")
print(" v v")
print("  v")
print("")
print("-"*15)
print("v"," "*13,"v")
print("","v"," "*11,"v")
print("","v"," "*9,"v")
print(" ","v"," "*7,"v")
print("  ","v"," "*3,"v")
print("   ","v"," ","v")
print("     ","v")
print("test\t-2")'''
import time
import calendar
print (time)
print (calendar)
import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d"))
#print (now.strftime - 2004.0)